var x = 4;
var y = -x;
console.log("Value of X: ", x);
console.log("Value of Y", y);
var msg = "hello" + "world";
console.log(msg);
var num = -2;
var result = num > 0 ? "positive" : "non-positive";
console.log(result);
var num = 12;
console.log(typeof num);
